# Generated by Django 3.0.2 on 2021-02-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0011_remove_design_products'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='product',
        ),
        migrations.AddField(
            model_name='profile',
            name='design',
            field=models.ManyToManyField(blank=True, to='design.Design'),
        ),
    ]
