# Generated by Django 3.0.2 on 2020-09-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
