# Generated by Django 3.0.2 on 2020-09-26 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_design_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
