# Generated by Django 3.0.2 on 2020-10-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_design_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
