# Generated by Django 3.0.2 on 2020-10-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0006_auto_20201017_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='price',
            field=models.IntegerField(),
        ),
    ]
