# Generated by Django 3.0.2 on 2020-10-17 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0007_auto_20201017_1015'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='design',
            table='Design',
        ),
    ]
