# Generated by Django 3.0.2 on 2020-10-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0008_auto_20201017_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='products',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
