# Generated by Django 3.0.2 on 2020-10-20 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0009_design_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='is_published',
        ),
    ]
