# Generated by Django 3.0.2 on 2020-11-02 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0010_remove_design_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='products',
        ),
    ]
