# Generated by Django 3.0.2 on 2021-02-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0011_remove_design_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='product',
        ),
    ]
