# Generated by Django 3.0.2 on 2021-02-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0012_remove_design_product'),
        ('order', '0005_auto_20210216_1926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Design',
        ),
    ]
