# Generated by Django 3.0.2 on 2020-09-25 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variety_type',
            name='variety',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variety_type',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='Variety',
        ),
        migrations.DeleteModel(
            name='Variety_Type',
        ),
    ]
