# Generated by Django 3.0.2 on 2020-09-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20200930_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='product',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='product_id',
            field=models.IntegerField(),
        ),
    ]
