# Generated by Django 3.0.2 on 2020-09-30 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20200930_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='product_id',
        ),
    ]
