# Generated by Django 3.0.2 on 2020-09-30 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_contact_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='product_id',
        ),
    ]
