# Generated by Django 3.0.2 on 2021-02-15 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0011_remove_design_products'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='design',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.Design'),
        ),
    ]
