# Generated by Django 3.0.2 on 2021-02-15 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitem_design'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='design',
        ),
    ]
