# Generated by Django 3.0.2 on 2021-02-16 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200925_1300'),
        ('order', '0004_auto_20210215_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='design',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
    ]
