# Generated by Django 3.0.2 on 2021-03-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20210301_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default=1615117588.9584107, max_length=255),
        ),
    ]
